import React from "react";


const PrivacyPolicyComponent = () => {
    return (
        <>
            <h1>Privacy Policy</h1>
            <p>Last updated: December 14, 2021</p>
            <p>This Privacy Policy describes our policies on the use and collection of personal data through your
                interactions with the Movie review site.</p>
            <p>We use Your Personal data to run our service and power its features as related to movies and movie
                reviewing. By using the Service, You agree to the collection and use of information in accordance with
                this Privacy Policy.</p>
            <h2>Definitions</h2>
            <p>For the purposes of this Privacy Policy:</p>
            <ul>
                <li>
                    <p><strong>Account</strong> means a unique account created for You to access our Service or parts of
                        our Service.</p>
                </li>
                <li>
                    <p><strong>Company</strong> (referred to as either "the Company", "We", "Us" or "Our" in this
                        Agreement) refers to Movie Reviews.</p>
                </li>
                <li>
                    <p><strong>Cookies</strong> are small files that are placed on Your computer, mobile device or any
                        other device by a website, containing the details of Your browsing history on that website among
                        its many uses.</p>
                </li>
                <li>
                    <p><strong>Country</strong> refers to: Massachusetts, United States</p>
                </li>
                <li>
                    <p><strong>Device</strong> means any device that can access the Service such as a computer, a
                        cellphone or a digital tablet.</p>
                </li>
                <li>
                    <p><strong>Personal Data</strong> is any information that relates to an identified or identifiable
                        individual.</p>
                </li>
                <li>
                    <p><strong>Service</strong> refers to the Website.</p>
                </li>
                <li>
                    <p><strong>Service Provider</strong> means any natural or legal person who processes the data on
                        behalf of the Company. It refers to third-party companies or individuals employed by the Company
                        to facilitate the Service, to provide the Service on behalf of the Company, to perform services
                        related to the Service or to assist the Company in analyzing how the Service is used.</p>
                </li>
                <li>
                    <p><strong>Usage Data</strong> refers to data collected automatically, either generated by the use
                        of the Service or from the Service infrastructure itself (for example, the duration of a page
                        visit).</p>
                </li>
                <li>
                    <p><strong>You</strong> means the individual accessing or using the Service, or the company, or
                        other legal entity on behalf of which such individual is accessing or using the Service, as
                        applicable.</p>
                </li>
            </ul>
            <h1>Collecting and Using Your Personal Data</h1>
            <h2>Types of Data Collected</h2>
            <p> The Movie Review site may collect personal data related but not limited to the following:</p>
            <h3>Usage Data</h3>
            <p>Usage Data is not collected automatically when using the Service since the operation of the service is
                currently not dependent on usage data, but by using the site you consent to having your usage data
                collected.
                Usage data will be used to analyze users to improve the functionality of the site</p>
            <h3>Tracking Technologies and Cookies</h3>
            <p>We use Cookies and similar tracking technologies to track the activity on Our Service and store certain
                information. Tracking technologies used are beacons, tags, and scripts to collect and track information
                and to improve and analyze Our Service</p>
            <ul>
                <li><strong>Cookies or Browser Cookies.</strong> A cookie is a small file placed on Your Device. You can
                    instruct Your browser to refuse all Cookies or to indicate when a Cookie is being sent. However, if
                    You do not accept Cookies, You may not be able to use some parts of our Service. Unless you have
                    adjusted Your browser setting so that it will refuse Cookies, our Service may use Cookies.
                </li>
                <li><strong>Flash Cookies.</strong> Certain features of our Service may use local stored objects (or
                    Flash Cookies) to collect and store information about Your preferences or Your activity on our
                    Service. Flash Cookies are not managed by the same browser settings as those used for Browser
                    Cookies. For more information on how You can delete Flash Cookies, please read &quot;Where can I
                    change the settings for disabling, or deleting local shared objects?&quot; available at <a
                        href="https://helpx.adobe.com/flash-player/kb/disable-local-shared-objects-flash.html#main_Where_can_I_change_the_settings_for_disabling__or_deleting_local_shared_objects_"
                        rel="external nofollow noopener"
                        target="_blank">https://helpx.adobe.com/flash-player/kb/disable-local-shared-objects-flash.html#main_Where_can_I_change_the_settings_for_disabling__or_deleting_local_shared_objects_</a>
                </li>
                <li><strong>Web Beacons.</strong> Certain sections of our Service and our emails may contain small
                    electronic files known as web beacons (also referred to as clear gifs, pixel tags, and single-pixel
                    gifs) that permit the Company, for example, to count users who have visited those pages or opened an
                    email and for other related website statistics (for example, recording the popularity of a certain
                    section and verifying system and server integrity).
                </li>
            </ul>
            <h2>Use of Your Personal Data</h2>
            <p>The Company may use Personal Data for the following purposes:</p>
            <ul>
                <li>
                    <p><strong>To provide and maintain our Service</strong> (generate movie reviews and likes).</p>
                </li>
                <li>
                    <p><strong>To manage Your Account:</strong> The Personal Data You provide can give You access to
                        different functionalities of the Service that are available to You as a registered user.</p>
                </li>
            </ul>
            <p>We may share Your personal information in the following situations:</p>
            <ul>
                <li><strong>With other users:</strong> when You share personal information other users will see your
                    profile, but personal identity information such as email is hidden.
                </li>
            </ul>
            <h2>Retention of Your Personal Data</h2>
            <p>Your personal data is retained to keep the service running and to aggregate data with other users to
                display metrics for the site.</p>
            <h2>Security of Your Personal Data</h2>
            <p>The security of Your Personal Data is important to Us, but remember that no method of transmission over
                the Internet, or method of electronic storage is 100% secure. While We strive to use commercially
                acceptable means to protect Your Personal Data, We cannot guarantee its absolute security.</p>
            <h1>Links to Other Websites</h1>
            <p>Our Service does not currently contain links to other websites that are not operated by Us. However,
                third-party links can be added in the future. We strongly advise You to review the Privacy Policy of
                every site You visit.</p>
            <p>We have no control over and assume no responsibility for the content, privacy policies or practices of
                any third party sites or services.</p>
            <h1>Changes to this Privacy Policy</h1>
            <p>We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new
                Privacy Policy on this page.</p>
            <p>You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy
                Policy are effective when they are posted on this page.</p>

        </>
    )
}

export default PrivacyPolicyComponent;
